### PR TITLE
Date picker improvements

### PR DESCRIPTION
**Pull request by anisha-deverashetty**
Small improvements:

- When we use multiple same instances of date picker in a page, then clicking anywhere inside will close it. So needs stop propagation on click.

- Clicking prev/next month as soon as opening datepicker, sends the showError msg. Fix it so that showError is send only during onBlur when the calendar is closed or after choosing a date.

### CODE REVIEW

**Review by fredrikloberg — COMMENTED** [review]
Why is onBlur needed/what is it used for?

**Comment by anisha-deverashetty** [comment]
> Why is onBlur needed/what is it used for?

It is used to set the `error` to true/false. I think better to rename it to showError or something.

**Review by fredrikloberg — APPROVED** [review]
Could you explain the point with multiple instances further? I dont quite see why having multiple makes it close when clicking inside 🤔

**Comment by anisha-deverashetty** [comment]
> Could you explain the point with multiple instances further? I dont quite see why having multiple makes it close when clicking inside 🤔
Having multiple is fine but have multiple same instance is causing issue. For example in the Inventory asset details page we have 3 same datepicker instance for invoice date to support responsive style. We always show 1 and hide the rest. When clicking inside the datepicker, we are getting the "outsideclick" event from hidden ones which will set `onFocus=False` and makes datepicker to close.

**Pull request merged**
