### PR TITLE
Add one-eye icon used in new designs

### PR DESCRIPTION
**Pull request by rogerab79**
Elmify the one eye-icon from figma
+ Also add icon names underneath misc icons (full conversion in another PR).
image

### CODE REVIEW

**Review by morteako — APPROVED** [review]
LGTM

**Comment by fonnes** [comment]
@rogerab79 if it is not too much work can you add the name beneath the icon? It's always annoying to try to find the proper name when using them 😅

**Comment by rogerab79** [comment]
> @rogerab79 if it is not too much work can you add the name beneath the icon? It's always annoying to try to find the proper name when using them 😅

How would this look like: Prob. need to ask others if this is appropriate layout.
image

**Comment by fonnes** [comment]
Really good 🙌

**Review by sarastorbjork — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
